INSERT INTO PERSON_ENTITIES (AGE,NAME,SURNAME)
VALUES(24,'Roosi','Remmelgas');
INSERT INTO PERSON_ENTITIES (AGE,NAME,SURNAME)
VALUES(25,'Reemu','Rein');
INSERT INTO PERSON_ENTITIES (AGE,NAME,SURNAME)
VALUES(26,'Õnneke','Lina');

INSERT INTO PRODUCT_ENTITIES(PRICE,PRODUCT_NAME)
VALUES(20,'towel');
INSERT INTO PRODUCT_ENTITIES(PRICE,PRODUCT_NAME)
VALUES(6.50,'mug');
INSERT INTO PRODUCT_ENTITIES(PRICE,PRODUCT_NAME)
VALUES(11.80,'bowl');