INSERT INTO PERSON_ENTITIES (AGE,NAME,SURNAME)
VALUES(24,'Roosi','Remmelgas');
INSERT INTO PERSON_ENTITIES (AGE,NAME,SURNAME)
VALUES(25,'Reemu','Rein');
INSERT INTO PERSON_ENTITIES (AGE,NAME,SURNAME)
VALUES(26,'Õnneke','Lina');